apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    owner: leha
spec:
  replicas: 10
  selector:
    matchLabels:
      project: super-prj
  template:
    metadata:
      labels:
        project: super-prj
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: nginx-deploy
  minReplicas: 10
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
