apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      project: web-project
  template:
    metadata:
      labels:
        project: web-project
    spec:
      containers:
        - name: apache
          image: nginx
          ports:
            - containerPort: 80
        - name: tomcat
          image: tomcat
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-web
  labels:
    owner: leha
spec:
  type: NodePort
  selector:
    project: web-project
  ports:
    - name: apache-listener
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
    - name: tomcat-listener
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008