apiVersion: v1
kind: Pod
metadata:
  name: flatris
  labels:
    env: prod
    owner: leha
spec:
  containers:
    - name: flatris-container
      image: nebantepermanentnopls/flatris
      ports:
        - containerPort: 3000