apiVersion: v1
kind: Service
metadata:
  name: nginx-sercie
  labels:
    owner: leha
spec:
  selector:
    project: super-prj
  ports:
    - name: nginx-port
      protocol: TCP
      port: 88          #service port
      targetPort: 80    #pod port
  type: LoadBalancer